export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const INCREASE_QTY = "INCREASE_QTY";
export const DECREASE_QTY = "DECREASE_QTY";
export const CLEAR_CART = "CLEAR_CART";



export const PLACE_ORDER_START = "PLACE_ORDER_START";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";
export const GET_PAST_ORDERS_START = "GET_PAST_ORDERS_START";
export const GET_PAST_ORDERS_SUCCESS = "GET_PAST_ORDERS_SUCCESS";
export const GET_PAST_ORDERS_FAIL = "GET_PAST_ORDERS_FAIL";
export const DELETE_ORDER_START = "DELETE_ORDER_START";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";